'use strict';

/**
 * engine.devig.test.js — golden-vector tests for Shin and multiplicative
 * de-vig. Zero deps, no DB / network, same shape as engine.dixoncoles.test.js.
 *
 * The GOLDEN constants below were produced by an INDEPENDENT reference
 * implementation — Python/mpmath at 40 decimal digits, solving the Shin
 * constraint with Anderson's method rather than the bisection lib/devig.js
 * uses. That matters: a golden generated by the code under test only proves the
 * code has not changed, not that it is right. These agree to 1e-9 across a
 * different language, a different precision and a different root-finder.
 *
 * The same vectors are duplicated in eve-frontend/lib/devig.test.ts. If either
 * port drifts, its test breaks — the arrangement dixonColes already uses.
 */

const assert = require('assert');
const dv = require('./lib/devig');

// ── GOLDEN VECTORS (mirrored in eve-frontend/lib/devig.test.ts) ──────────────
// Source: mpmath, 40 dps, solver='anderson'.
const G = {
  // A routine 3-way book, 4.81% overround. Same prices as the dixonColes
  // multiplicative golden, so the `mult` row below is checkable against it.
  threeWay: {
    odds: [2.10, 3.40, 3.60],
    overround: 1.048085901,
    z: 0.0240828367317,
    shin: [0.458665716, 0.2787376371, 0.2625966469],
    mult: [0.4543429844, 0.280623608, 0.2650334076],
  },
  // A lopsided 3-way — short favourite, 11.0 outsider. This is the shape that
  // manufactured the -70% longshot book under multiplicative de-vig.
  lopsided: {
    odds: [1.30, 5.50, 11.00],
    overround: 1.041958042,
    z: 0.0215427761683,
    shin: [0.750905445, 0.1693976081, 0.07969694682],
    mult: [0.7382550336, 0.1744966443, 0.08724832215],
  },
  // 2-way, symmetric. Shin and multiplicative MUST agree here: with equal
  // prices there is no outsider to load margin onto.
  twoWaySymmetric: {
    odds: [1.90, 1.90],
    overround: 1.052631579,
    z: 0.0526315789474,
    shin: [0.5, 0.5],
    mult: [0.5, 0.5],
  },
  // 2-way, extreme. The clearest demonstration in the suite: Shin prices the
  // 34.0 shot at 1.97% where multiplicative says 2.88% — a third lower.
  twoWayExtreme: {
    odds: [1.01, 34.0],
    overround: 1.019510775,
    z: 0.0239815149994,
    shin: [0.9803436226, 0.0196563774],
    mult: [0.9711510997, 0.02884890031],
  },
};

let passed = 0, failed = 0;
function test(label, fn) {
  try { fn(); console.log(`  ✓ ${label}`); passed++; }
  catch (err) { console.error(`  ✗ ${label}\n    ${err.message}`); failed++; }
}
const close = (a, b, tol = 1e-9) =>
  assert.ok(Math.abs(a - b) < tol, `expected ${b}, got ${a} (diff ${Math.abs(a - b)})`);
const closeVec = (a, b, tol = 1e-9) => {
  assert.strictEqual(a.length, b.length, `length ${a.length} != ${b.length}`);
  a.forEach((x, i) => close(x, b[i], tol));
};
const sum = xs => xs.reduce((s, x) => s + x, 0);

// ── Hand-checked golden output ──────────────────────────────────────────────
console.log('\nde-vig — golden vectors against an independent implementation');

for (const [name, g] of Object.entries(G)) {
  test(`${name}: Shin matches the mpmath reference to 1e-9`, () => {
    const r = dv.shinDevig(g.odds);
    assert.strictEqual(r.reason, null, `unexpected rejection: ${r.reason}`);
    close(r.overround, g.overround, 1e-9);
    close(r.z, g.z, 1e-9);
    closeVec(r.probs, g.shin);
  });

  test(`${name}: multiplicative matches the reference to 1e-9`, () => {
    const r = dv.multiplicativeDevig(g.odds);
    assert.strictEqual(r.reason, null);
    closeVec(r.probs, g.mult);
    assert.strictEqual(r.z, 0, 'multiplicative has no insider fraction');
  });
}

test('the 3-way multiplicative golden agrees with dixonColes.js', () => {
  // dixonColes' devig_2_1__3_4__3_6 golden, verbatim, to 1e-5 as that file states.
  closeVec(dv.multiplicativeDevig([2.10, 3.40, 3.60]).probs,
           [0.454343, 0.280624, 0.265033], 1e-5);
});

// ── The property the whole architecture rests on ────────────────────────────
console.log('\nde-vig — Shin shortens the longest price (the reason it is used)');

test('high-margin 3-way: Shin gives the outsider LESS than multiplicative', () => {
  // 12.4% overround, deliberately fat — margin this size is where the two
  // methods diverge most.
  const odds = [1.50, 4.00, 9.00];
  const s = dv.shinDevig(odds).probs;
  const m = dv.multiplicativeDevig(odds).probs;
  const longest = odds.indexOf(Math.max(...odds));
  assert.ok(s[longest] < m[longest],
    `Shin ${s[longest]} should be below multiplicative ${m[longest]} on the outsider`);
  // ...and correspondingly MORE to the favourite.
  const shortest = odds.indexOf(Math.min(...odds));
  assert.ok(s[shortest] > m[shortest],
    `Shin ${s[shortest]} should exceed multiplicative ${m[shortest]} on the favourite`);
});

test('the gap widens with the margin — it is the margin being redistributed', () => {
  // Build books from ONE fair vector at increasing margins, so the only thing
  // varying is the overround. (Hand-picked prices are a trap here: [2.00, 3.90,
  // 4.20] looks like a normal book and is actually a 0.55% ARB, where there is
  // no margin to redistribute and the gap is correctly zero.)
  const FAIR = [0.50, 0.26, 0.24];
  const bookAt = margin => FAIR.map(p => 1 / (p * (1 + margin)));
  const gapAt = margin => {
    const odds = bookAt(margin);
    const longest = odds.indexOf(Math.max(...odds));
    return dv.multiplicativeDevig(odds).probs[longest] - dv.shinDevig(odds).probs[longest];
  };
  const gaps = [0.02, 0.05, 0.10, 0.20].map(gapAt);
  assert.ok(gaps[0] > 0, 'even a 2% book should shift some probability off the outsider');
  for (let i = 1; i < gaps.length; i++) {
    assert.ok(gaps[i] > gaps[i - 1],
      `gap should grow with margin, got ${JSON.stringify(gaps)}`);
  }
});

test('a longshot loses a THIRD of its implied probability on a fat 2-way', () => {
  // The headline number: this is the mechanism behind 49 flagged longshots,
  // 1 winner, -70% yield.
  const s = dv.shinDevig([1.01, 34.0]).probs[1];
  const m = dv.multiplicativeDevig([1.01, 34.0]).probs[1];
  assert.ok(s < m * 0.75, `Shin ${s} should be well under 75% of multiplicative ${m}`);
});

// ── Convergence to the proportional answer at zero margin ───────────────────
console.log('\nde-vig — Shin → multiplicative as margin → 0');

test('near-fair 3-way: the two agree to ~1e-6', () => {
  // Overround ~1.0000001. Chosen so the book is genuinely near-fair rather than
  // exactly fair, which would take the explicit NEAR_ZERO_MARGIN branch.
  const p = [0.5, 0.3, 0.2];
  const odds = p.map(x => 1 / (x * (1 + 1e-7)));
  const s = dv.shinDevig(odds).probs;
  const m = dv.multiplicativeDevig(odds).probs;
  closeVec(s, m, 1e-6);
});

test('exactly fair book: z is 0 and probs are the implied prices', () => {
  const odds = [2.0, 4.0, 4.0];   // Σ1/o = 1 exactly
  const r = dv.shinDevig(odds);
  close(r.overround, 1, 1e-15);
  assert.strictEqual(r.z, 0);
  closeVec(r.probs, [0.5, 0.25, 0.25], 1e-12);
});

test('symmetric book: Shin and multiplicative are identical at any margin', () => {
  // No outsider ⇒ nothing to redistribute, at 5% margin or 40%.
  for (const o of [1.90, 1.50, 1.05]) {
    closeVec(dv.shinDevig([o, o]).probs, dv.multiplicativeDevig([o, o]).probs, 1e-12);
  }
});

// ── The normalisation invariant ─────────────────────────────────────────────
console.log('\nde-vig — probabilities sum to 1.0 ± 1e-9 in all cases');

test('across a sweep of 2- and 3-way books, both methods sum to 1', () => {
  const books = [];
  for (const a of [1.05, 1.3, 1.8, 2.5, 4.0, 9.0, 26.0]) {
    for (const b of [1.2, 2.0, 3.5, 7.0, 15.0, 51.0]) {
      books.push([a, b]);
      for (const c of [3.0, 5.5, 12.0, 34.0]) books.push([a, b, c]);
    }
  }
  let checked = 0;
  for (const book of books) {
    for (const fn of [dv.shinDevig, dv.multiplicativeDevig]) {
      const r = fn(book);
      if (r.probs === null) continue;      // rejected inputs are tested below
      close(sum(r.probs), 1, 1e-9);
      assert.ok(r.probs.every(p => p > 0 && p < 1),
        `book ${book} produced an out-of-range probability: ${r.probs}`);
      checked++;
    }
  }
  assert.ok(checked > 300, `expected a broad sweep, only checked ${checked}`);
});

test('z stays inside [0,1) and rises with the margin', () => {
  const zAt = odds => dv.shinDevig(odds).z;
  const zs = [
    zAt([2.02, 3.92, 4.05]),
    zAt([2.00, 3.85, 4.00]),
    zAt([1.95, 3.70, 3.85]),
    zAt([1.85, 3.45, 3.60]),
  ];
  zs.forEach(z => assert.ok(z >= 0 && z < 1, `z out of range: ${z}`));
  for (let i = 1; i < zs.length; i++) {
    assert.ok(zs[i] > zs[i - 1], `z should increase with margin: ${zs}`);
  }
});

// ── Arbitrage and degenerate input ──────────────────────────────────────────
console.log('\nde-vig — arbitrage and malformed input');

test('sub-1.0 overround is flagged as arbitrage, still normalised', () => {
  const odds = [2.20, 4.00, 4.50];   // Σ1/o = 0.9773
  for (const fn of [dv.shinDevig, dv.multiplicativeDevig]) {
    const r = fn(odds);
    assert.strictEqual(r.arbitrage, true, 'should flag arbitrage');
    assert.ok(r.overround < 1, `overround ${r.overround} should be below 1`);
    assert.ok(r.margin < 0, 'margin should be negative');
    close(sum(r.probs), 1, 1e-12);
    assert.strictEqual(r.z, 0, 'no insider fraction explains a negative margin');
  }
});

test('an overround book is NOT flagged as arbitrage', () => {
  assert.strictEqual(dv.shinDevig([2.10, 3.40, 3.60]).arbitrage, false);
});

test('missing, zero and junk prices reject the whole market', () => {
  // A partial de-vig is worse than none: it prices the absent leg at zero and
  // reports edge on everything that remains.
  const bad = [
    [2.1, null, 3.6],
    [2.1, 0, 3.6],
    [2.1, undefined, 3.6],
    [2.1, NaN, 3.6],
    [2.1, '', 3.6],
    [2.1, 'abc', 3.6],
    [2.1, -3.4, 3.6],
    [2.1, 1.0, 3.6],       // 1.0 is not a price
    [2.1, 0.85, 3.6],      // below 1.0 is not a price
    [2.1, Infinity, 3.6],
  ];
  for (const book of bad) {
    for (const fn of [dv.shinDevig, dv.multiplicativeDevig]) {
      const r = fn(book);
      assert.strictEqual(r.probs, null, `${JSON.stringify(book)} should be rejected`);
      assert.ok(/incomplete market/.test(r.reason), `unexpected reason: ${r.reason}`);
    }
  }
});

test('a market of fewer than two outcomes is rejected', () => {
  for (const bad of [[], [2.0], null, undefined, 'nope', 42]) {
    for (const fn of [dv.shinDevig, dv.multiplicativeDevig]) {
      const r = fn(bad);
      assert.strictEqual(r.probs, null, `${JSON.stringify(bad)} should be rejected`);
      assert.ok(r.reason, 'a rejection must carry a reason');
    }
  }
});

test('numeric strings are accepted — Postgres numerics arrive as strings', () => {
  const a = dv.shinDevig(['2.10', '3.40', '3.60']).probs;
  const b = dv.shinDevig([2.10, 3.40, 3.60]).probs;
  closeVec(a, b, 1e-15);
});

test('markets wider than three outcomes solve', () => {
  // Correct-score / first-scorer shaped: many legs, fat margin. Built from a
  // fair vector so the eight prices are a COMPLETE market — eight plausible
  // -looking prices picked by hand sum to well under 1 and are not a book.
  const fair = [0.28, 0.20, 0.15, 0.12, 0.10, 0.07, 0.05, 0.03];
  const odds = fair.map(p => 1 / (p * 1.15));
  const r = dv.shinDevig(odds);
  close(sum(r.probs), 1, 1e-9);
  assert.ok(r.z > 0, 'a fat multi-way book must have a positive insider fraction');
  const m = dv.multiplicativeDevig(odds).probs;
  assert.ok(r.probs[7] < m[7], 'the longest of eight prices should still be shortened');
});

// ── Helpers ─────────────────────────────────────────────────────────────────
console.log('\nde-vig — helpers');

test('fairPrice inverts a probability and refuses nonsense', () => {
  close(dv.fairPrice(0.25), 4.0, 1e-12);
  assert.strictEqual(dv.fairPrice(0), null);
  assert.strictEqual(dv.fairPrice(-0.1), null);
  assert.strictEqual(dv.fairPrice(NaN), null);
  assert.strictEqual(dv.fairPrice(null), null);
});

test('toPrice rejects the Number(null) family', () => {
  assert.strictEqual(dv.toPrice(null), null);
  assert.strictEqual(dv.toPrice(''), null);
  assert.strictEqual(dv.toPrice('  '), null);
  assert.strictEqual(dv.toPrice(0), null);
  assert.strictEqual(dv.toPrice(1), null);
  assert.strictEqual(dv.toPrice('2.5'), 2.5);
});

console.log(`\n${failed === 0 ? '✓' : '✗'} devig: ${passed} passed, ${failed} failed\n`);
process.exit(failed === 0 ? 0 : 1);
