'use strict';

/**
 * lib/modelVeto.js — THE MODEL'S ONLY REMAINING POWER.
 *
 * Under the ruling of 6 Aug 2026 the model does not price, does not flag and
 * does not score. It holds a veto. This module is that veto and nothing else:
 * every function here returns a boolean or a reason, never a number that could
 * reach an edge, a price or a MES. `shouldSuppress()` can only ever turn a
 * signal OFF — there is no input to it that turns one ON.
 *
 * THE PREMISE. Over 44,820 settled selections, model-market disagreement is
 * anti-predictive: the further the model strays from the closing line, the more
 * often the MARKET turns out to be closer to the truth.
 *
 *     gap        n        market right   model Brier / market Brier
 *     <3pp       16,416   48.5%          0.2013 / 0.2010
 *     3-6pp      10,849   49.0%          0.2026 / 0.2014
 *     6-10pp      7,793   57.0%          0.2116 / 0.2063
 *     10-15pp     5,303   61.4%          0.2248 / 0.2102
 *     15pp+       4,459   65.1%          0.2523 / 0.2069
 *
 * (Live figures in `disagreement_calibration`; the table is the authority, this
 * comment is a snapshot of the 6 Aug 2026 refresh.) The gradient is monotone,
 * enormous and survives the switch from proportional to Shin de-vig. A large
 * gap means the model has missed something the market can see — a lineup, a
 * rotation, a dead rubber — and the reasonable response is to stand aside.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * AND YET: THE VETO IS NOT EMPIRICALLY SUPPORTED AS A YIELD FILTER. READ THIS
 * BEFORE LOWERING THETA.
 *
 * The gradient above is about ACCURACY — whose probability sat closer to the
 * result. It does not carry over to PROFIT on the market-anchored board, and
 * measuring it directly says so. Over the 1,337 gated selections in the
 * seven-season corpus (Shin-de-vigged Pinnacle open, best-of-panel price):
 *
 *     theta   kept    yield_kept   suppressed   yield_suppressed   t
 *     none    1337     +4.84%            —             —            —
 *     0.04     497     +7.30%          840          +3.38%        0.80
 *     0.08     878     +3.93%          459          +6.58%        1.23
 *     0.14    1145     +3.61%          192         +12.18%        1.58
 *     0.20    1277     +4.64%           60          +8.93%        0.64
 *     0.26    1315     +5.51%           22         -35.45%       -1.85
 *
 * At every threshold from 0.02 to 0.20 the SUPPRESSED set is PROFITABLE — often
 * more profitable than the set kept. A veto there does not remove losers, it
 * throws away winners. No t-statistic in the sweep reaches 2 in either
 * direction; the whole curve is consistent with noise.
 *
 * WHY THE TWO FINDINGS DO NOT CONTRADICT EACH OTHER. They are claims about
 * different things. Finding #2 says the model is a worse forecaster when it
 * disagrees. The veto premise says selections the model disagrees about are bad
 * BETS. But a market-anchored signal is generated by a soft book disagreeing
 * with Pinnacle — the model is not in that comparison at any point. Whether the
 * model also happens to be confused about the fixture is close to orthogonal to
 * whether Bet365 has hung a stale price. The model being wrong is simply not
 * evidence about the thing the signal is measuring.
 *
 * WHAT THETA IS SET TO, AND WHY. 0.26 — high enough that it fires on 1.6% of
 * signals and only on divergence so extreme (26 percentage points) that it
 * indicates the model has no information about the fixture at all. It is a
 * PATHOLOGY GUARD, not an edge filter: it exists to stop a signal going out on
 * a match where the model has visibly lost the plot, and it is priced to cost
 * almost nothing if it is worthless, which on this evidence it may well be.
 *
 * 0.26 is also the only region of the sweep where the suppressed set is
 * negative, and that is worth exactly as much as its t-statistic of -1.85 over
 * 22 selections: it is the best of eighteen candidates, which is a description
 * of overfitting. DO NOT lower theta to "make the veto do more work". Every
 * threshold that suppresses meaningfully suppresses money.
 *
 * The corpus is also IN-SAMPLE — research_dc_preds is fitted per season — so
 * the model is being graded on matches it was fitted on. That flatters the
 * model, which means the true divergence gradient is at least this steep and
 * the veto's case is, if anything, weaker than it looks here.
 */

/**
 * Divergence above which a signal is suppressed. See the header — this is a
 * pathology guard set deliberately high, not a fitted optimum, and lowering it
 * has been measured to destroy value.
 */
const DEFAULT_THETA = 0.26;

/** Every theta swept on 6 Aug 2026, kept so a re-fit can be compared like for
 *  like rather than re-deciding the grid. */
const THETA_GRID = Object.freeze([
  0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14, 0.16,
  0.18, 0.20, 0.22, 0.24, 0.26, 0.28, 0.30, 0.32, 0.34, 0.36,
]);

/**
 * Should this signal be suppressed?
 *
 * Returns a plain boolean plus the reason and the measured gap, for the audit
 * trail. NOTE THE FAIL-OPEN: if the model has no opinion, or its number is
 * unusable, the signal is NOT suppressed. That is the opposite of
 * `previewLimit()` and `isPublished()`, which fail closed, and it is deliberate
 * — those gates decide whether a CLAIM may be made, and an unheard-of claim
 * must not publish. This one decides whether a market-derived signal that has
 * already passed its own gate should be withheld on the model's say-so. A model
 * that has said nothing has not objected, and silence is not an objection. A
 * missing model probability must never be able to empty the board.
 *
 * @param {object} x
 * @param {number|null|undefined} x.modelProb  the model's probability for THIS selection
 * @param {number} x.fairProb                  Shin-de-vigged anchor probability
 * @param {number} [x.theta]
 * @returns {{suppress: boolean, gap: number|null, theta: number, reason: string|null}}
 */
function shouldSuppress({ modelProb, fairProb, theta = DEFAULT_THETA }) {
  const m = toProb(modelProb);
  const f = toProb(fairProb);

  if (m === null) {
    return { suppress: false, gap: null, theta, reason: null };
  }
  if (f === null) {
    // No anchor means there was no signal to suppress in the first place; the
    // market-anchored path will have rejected it long before here.
    return { suppress: false, gap: null, theta, reason: null };
  }

  const gap = Math.abs(m - f);
  if (gap > theta) {
    return {
      suppress: true,
      gap,
      theta,
      reason: `model diverges from the market by ${(gap * 100).toFixed(1)}pp (threshold ${(theta * 100).toFixed(0)}pp) — treated as the model having no read on this fixture`,
    };
  }
  return { suppress: false, gap, theta, reason: null };
}

/**
 * Coerce a probability. Not `Number(x)`: `Number(null)` is 0, and a model
 * probability of 0 is a maximal divergence from any fair price, so the
 * Number(null) bug here would suppress the entire board.
 */
function toProb(x) {
  if (x == null) return null;
  if (typeof x === 'string' && x.trim() === '') return null;
  const n = typeof x === 'number' ? x : Number(x);
  if (!Number.isFinite(n) || n < 0 || n > 1) return null;
  return n;
}

/**
 * The disagreement gap for display. Returns null when the model has no usable
 * probability, so a caller cannot render "0.0pp apart" for "we do not know".
 */
function disagreementGap(modelProb, fairProb) {
  const m = toProb(modelProb), f = toProb(fairProb);
  if (m === null || f === null) return null;
  return Math.abs(m - f);
}

/**
 * Below this gap the scorecard is NOT shown to a subscriber.
 *
 * In the <3pp and 3-6pp buckets the two forecasters are statistically tied
 * (Brier 0.2013 vs 0.2010, and 0.2026 vs 0.2014). The "51.5% model right" in
 * the top bucket is a composition artifact of counting strictly-closer, not
 * evidence the model wins — and putting it in front of a reader states, in the
 * only way a reader will parse it, that the model beats the market. It does
 * not. Above 6pp the gradient is real and the scorecard says something true.
 */
const SCORECARD_MIN_GAP = 0.06;

/** May the disagreement scorecard be shown for this gap? */
function scorecardVisible(gap) {
  return typeof gap === 'number' && Number.isFinite(gap) && gap >= SCORECARD_MIN_GAP;
}

module.exports = {
  shouldSuppress,
  disagreementGap,
  scorecardVisible,
  DEFAULT_THETA,
  THETA_GRID,
  SCORECARD_MIN_GAP,
};
