/**
 * ensemble/inference.js — ML Ensemble Inference Wrapper
 *
 * Loads XGBoost (Match Odds) and LightGBM (BTTS, Over/Under) models exported
 * as ONNX format by the Python training pipeline (train.py).
 *
 * RUNTIME BEHAVIOUR:
 *   - If ONNX model files are present → runs ML inference (ML_ENSEMBLE architecture)
 *   - If models are absent or input completeness < threshold → returns null
 *     and computeValues.js falls back to Dixon-Coles (DIXON_COLES architecture)
 *
 * MODEL FILES (generated by ensemble/train.py after training):
 *   ensemble/models/match_odds.onnx
 *   ensemble/models/btts.onnx
 *   ensemble/models/over_under.onnx
 *
 * OUTPUT:
 *   {
 *     home:  number,   // P(home win)
 *     draw:  number,   // P(draw)
 *     away:  number,   // P(away win)
 *     btts:  number,   // P(BTTS yes)
 *     over:  number,   // P(over 2.5 goals)
 *     architecture: 'ML_ENSEMBLE',
 *   }
 */

'use strict';

const path = require('path');
const fs   = require('fs');

const MODEL_DIR = path.join(__dirname, 'models');

// Lazy-load onnxruntime-node only if installed (optional dependency).
let ort = null;
function getOrt() {
  if (ort) return ort;
  try {
    ort = require('onnxruntime-node');
  } catch {
    ort = null;
  }
  return ort;
}

// Cache loaded sessions across calls (expensive to init on every match).
const sessionCache = {};

async function loadSession(name) {
  if (sessionCache[name]) return sessionCache[name];
  const runtime = getOrt();
  if (!runtime) return null;

  const modelPath = path.join(MODEL_DIR, `${name}.onnx`);
  if (!fs.existsSync(modelPath)) return null;

  try {
    const session = await runtime.InferenceSession.create(modelPath);
    sessionCache[name] = session;
    return session;
  } catch (err) {
    console.warn(`[ensemble] failed to load ${name}.onnx:`, err.message);
    return null;
  }
}

/**
 * Run ONNX inference for a single model.
 * @param {string} modelName  - 'match_odds' | 'btts' | 'over_under'
 * @param {number[]} features - flat float32 feature vector
 * @returns {number[] | null}  probability array or null on failure
 */
async function runModel(modelName, features) {
  const session = await loadSession(modelName);
  if (!session) return null;

  const runtime = getOrt();
  try {
    const inputName = session.inputNames[0];
    const tensor = new runtime.Tensor('float32', Float32Array.from(features), [1, features.length]);
    const results = await session.run({ [inputName]: tensor });

    // ONNX classifiers output probabilities under 'probabilities' or the first output name.
    const probKey = session.outputNames.find(n => n.includes('prob')) ?? session.outputNames[0];
    return Array.from(results[probKey].data);
  } catch (err) {
    console.warn(`[ensemble] inference error (${modelName}):`, err.message);
    return null;
  }
}

/**
 * Run all three ensemble models for a feature vector.
 * Returns null if any critical model fails or ONNX is not available.
 *
 * @param {number[]} features      - 22-dim feature vector from features.js
 * @param {number}   completeness  - data completeness [0,1] from features.js
 * @param {number}   minCompleteness - threshold below which we refuse to run
 * @returns {object|null}
 */
async function ensembleInference(features, completeness, minCompleteness = 0.60) {
  // Refuse to run on sparse data — fallback is better than a misleading prediction.
  if (completeness < minCompleteness) {
    console.log(`[ensemble] skipping — feature completeness ${(completeness * 100).toFixed(0)}% < ${(minCompleteness * 100).toFixed(0)}% threshold`);
    return null;
  }

  // Check if models directory exists at all (avoids noisy errors on first run).
  if (!fs.existsSync(MODEL_DIR)) return null;

  const [matchProbs, bttsProbs, ouProbs] = await Promise.all([
    runModel('match_odds',  features),
    runModel('btts',        features),
    runModel('over_under',  features),
  ]);

  // Match odds model is required — no fallback for core 1X2.
  if (!matchProbs || matchProbs.length < 3) return null;

  return {
    // XGBoost multi:softprob output: [P(home), P(draw), P(away)]
    home: matchProbs[0],
    draw: matchProbs[1],
    away: matchProbs[2],
    // LightGBM binary output: [P(class=0), P(class=1)] — we want index 1
    btts: bttsProbs ? bttsProbs[1] : null,
    over: ouProbs   ? ouProbs[1]   : null,
    architecture: 'ML_ENSEMBLE',
  };
}

/**
 * Check whether trained models are present and onnxruntime is installed.
 * Used by computeValues.js startup log.
 */
function ensembleAvailable() {
  if (!getOrt()) return false;
  return ['match_odds', 'btts', 'over_under'].some(m =>
    fs.existsSync(path.join(MODEL_DIR, `${m}.onnx`))
  );
}

module.exports = { ensembleInference, ensembleAvailable };
